---
name: Acme-CPANAuthors-Russian
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: We are Russian CPAN authors
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Acme::CPANAuthors: 0.06
  Acme::CPANAuthors::Register: 0
build_requires:
  Test::More: 0
provides:
  Acme::CPANAuthors::Russian:
    file: lib/Acme/CPANAuthors/Russian.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
