---
name: Acme-CPANAuthors-Russian
version: 1.00
author:
  - 'Anatoly Sharifulin <sharifulin@gmail.com>'
  - "Zoffix <'zoffix@cpan.org'>"
abstract: We are Russian CPAN authors
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/sharifulin/acme-cpanauthors-russian/tree
build_requires:
  Test::More: 0
requires:
  Acme::CPANAuthors: 0
  Acme::CPANAuthors::Register: 0
  perl: 5.006
configure_requires:
  Module::Build: 0.35
provides:
  Acme::CPANAuthors::Russian:
    file: lib/Acme/CPANAuthors/Russian.pm
    version: 1.00
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - CPAN
  - CPAN authors
  - Russian
